"""Business memory: clients, interaction logs, and Dilshan delegation."""

from datetime import timezone

from sqlalchemy import select
from sqlalchemy.orm import Session

from . import obsidian
from .models import Client, ClientLog, Task, utcnow

STALE_CONTACT_DAYS = 14

DELEGATION_BRIEF = """---
type: delegation
owner: dilshan
created: {created}
---
# Task Brief: {title}

**From:** Izzy
**Owner:** Dilshan

## Goal
{details}

## Definition of done
- [ ] Work complete and checked
- [ ] One-line status posted back to Smart OS

## Notes
Generated by Smart OS CEO Layer. Reply with blockers early, not late.
"""


def create_client(db: Session, name: str, domain: str = "", mrr: float = 0.0,
                  status: str = "active", notes: str = "") -> Client:
    client = Client(name=name.strip(), domain=domain.strip(), mrr=mrr,
                    status=status, notes=notes)
    db.add(client)
    db.commit()
    return client


def list_clients(db: Session) -> list[Client]:
    return list(db.scalars(select(Client).order_by(Client.mrr.desc())))


def log_interaction(db: Session, client_id: int, entry: str,
                    kind: str = "note") -> ClientLog | None:
    if db.get(Client, client_id) is None:
        return None
    log = ClientLog(client_id=client_id, entry=entry.strip(), kind=kind)
    db.add(log)
    db.commit()
    return log


def client_health(db: Session) -> list[dict]:
    """Per-client snapshot with last-contact staleness for the brief."""
    now = utcnow()
    out = []
    for client in list_clients(db):
        last = db.scalar(
            select(ClientLog).where(ClientLog.client_id == client.id)
            .order_by(ClientLog.created_at.desc()).limit(1))
        days = None
        if last is not None:
            created = last.created_at
            if created.tzinfo is None:
                created = created.replace(tzinfo=timezone.utc)
            days = (now - created).days
        out.append({
            "id": client.id,
            "name": client.name,
            "mrr": client.mrr,
            "status": client.status,
            "days_since_contact": days,
            "needs_attention": client.status == "active" and (
                days is None or days >= STALE_CONTACT_DAYS),
        })
    return out


def delegate(db: Session, title: str, details: str = "",
             client_id: int | None = None, write_obsidian: bool = True) -> dict:
    """Create a Dilshan task plus a written brief in the Obsidian inbox."""
    task = Task(title=title.strip()[:500], details=details, owner="dilshan",
                category="seo_delivery", client_id=client_id)
    db.add(task)
    db.commit()
    note_path = None
    if write_obsidian:
        try:
            brief = DELEGATION_BRIEF.format(
                created=utcnow().date().isoformat(), title=title.strip(),
                details=details or title)
            safe_name = "".join(
                c for c in title[:60] if c.isalnum() or c in " -_").strip()
            note_path = obsidian.write_note(
                f"Delegation/{utcnow():%Y-%m-%d} {safe_name}.md", brief)
        except FileNotFoundError:
            note_path = None  # vault not configured; task still created
    return {"task_id": task.id, "obsidian_note": note_path}


def delegation_queue(db: Session) -> list[Task]:
    return list(db.scalars(
        select(Task).where(Task.owner == "dilshan", Task.status == "open")
        .order_by(Task.created_at)))
